site_name: docker-transmission-sabnzbd-openvpn
site_url: https://github.com/hvos234/docker-transmission-sabnzbd-openvpn/
repo_url: https://github.com/hvos234/docker-transmission-sabnzbd-openvpn/
theme:
  name: 'material'
markdown_extensions:
    - toc:
        permalink: True
        separator: "_"
nav:
   - 'Overview': 'index.md'
   - 'Image Building Blocks': 'building-blocks.md'
   - 'VPN and Networking': 'vpn-networking.md'
   - 'Running the container': 'run-container.md'
   - 'Supported providers': 'supported-providers.md'
   - 'Provider specific settings': 'provider-specific.md'
   - 'Configuration options': 'config-options.md'
   - 'Frequently asked questions': 'faq.md'
   - 'Debug your setup': 'debug.md'
   - 'Tips & Tricks': 'tips-tricks.md'
   - 'RSS plugin': 'rss-plugin.md'
   - 'Web Proxy': 'web-proxy.md'
plugins:
    - search